package club.yuxuan.yun.datesource.mysql.account;

import club.yuxuan.yun.model.account.AccountUser;

public interface AccountUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    int insert(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    int insertSelective(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    AccountUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountUser record);
}